version: "3.9"

services:
  web:
    image: ${{ secrets.DOCKER_USERNAME }}/course-platform:${GITHUB_SHA}
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
